#!/usr/bin/env node
/**
 * Netlify build: inject Render API URL into runtime-config.js.
 * Set SPOOKY_API_BASE in Netlify → Site settings → Environment variables.
 */
const fs = require("fs");
const path = require("path");

const base = (process.env.SPOOKY_API_BASE || "").trim().replace(/\/$/, "");
const out = path.join(__dirname, "..", "static", "js", "runtime-config.js");

const content =
  "// Generated by scripts/netlify-build.js — do not edit on Netlify deploys.\n" +
  "window.SPOOKY_API_BASE = " +
  JSON.stringify(base) +
  ";\n";

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, content);
console.log("[netlify-build] SPOOKY_API_BASE =", base || "(same-origin / empty)");
