#!/usr/bin/env node
/**
 * Netlify build: bake Render API URL into runtime-config.js.
 * Set SPOOKY_API_BASE in Netlify → Site settings → Environment variables.
 */
const fs = require("fs");
const path = require("path");

const base = (process.env.SPOOKY_API_BASE || "https://piyush-store.onrender.com")
  .trim()
  .replace(/\/$/, "");
const out = path.join(__dirname, "..", "static", "js", "runtime-config.js");

const content =
  "// Generated by scripts/netlify-build.js\n" +
  "(function (g) {\n" +
  "  var host = ((g.location && g.location.hostname) || \"\").toLowerCase();\n" +
  "  var isLocal = host === \"localhost\" || host === \"127.0.0.1\" || host === \"[::1]\";\n" +
  "  var isRenderApp = host.endsWith(\".onrender.com\");\n" +
  "  g.SPOOKY_API_BASE = isLocal || isRenderApp ? \"\" : " +
  JSON.stringify(base) +
  ";\n" +
  "})(typeof window !== \"undefined\" ? window : globalThis);\n";

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, content);
console.log("[netlify-build] production API =", base);
